
version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - mpich

python:
  system_packages: true
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false


