
# This workflow will install Python dependencies, run tests and lint with
# a single version of Python
#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/ \
#                         using-python-with-github-actions

name: Build

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv testenv
        . testenv/bin/activate
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements-ci.txt
    - name: Test with pytest
      env:
        LOC: testenv/lib/python3.9/site-packages
      run: |
        . testenv/bin/activate
        coverage run --include=$LOC/radical/analytics/* -m pytest -ra --timeout=600 -vvv --showlocals tests/
        coverage xml
    - uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv testenv
        . testenv/bin/activate
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements-ci.txt
    - name: Lint with flake8 and pylint
      run: |
        . testenv/bin/activate
        LOG=`git log -n 1 | grep Merge || echo 'no merging' && exit 0`
        NEW=`echo $LOG | cut -d ' ' -f2`
        OLD=`echo $LOG | cut -d ' ' -f3`
        test -z "$NEW" && NEW=HEAD
        test -z "$OLD" && OLD=HEAD
        DIFF=`git diff  --name-only --diff-filter=db $NEW..$OLD`
        DIFF=$(echo $DIFF | grep -o -e '\b[^ ]*.py\b' | sed "s|^|$PWD/|")
        test -z "$DIFF" && echo 'nothing to flake8' || flake8 $DIFF
        test -z "$DIFF" && echo 'nothing to pylint' || pylint $DIFF

